//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.IC.RecursosTxt.Querys {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportesCompraQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportesCompraQuery() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base.IC.RecursosTxt.Querys.ReportesCompraQuery", typeof(ReportesCompraQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 	p.Guid as Orden, u.Nombre as Comprador, u.NumeroDocumento as NumeroDocumento,u.Direccion as Direccion , u.Celular as Celular,co.Fecha as FechaCompra,sum(p.Cantidad) as CantidadComic,co.Total as TotalCompra FROM Usuario as u JOIN Pedido as p ON  u.ID = p.Usuario JOIN TipoDocumento as t ON u.TipoDocumento = t.Id JOIN Comic as c ON p.Comic = c.Id JOIN Compra as co ON co.Pedido = p.Guid WHERE u.NumeroDocumento = {0} AND p.Guid = &quot;{1}&quot;.
        /// </summary>
        public static string ReporteCompra {
            get {
                return ResourceManager.GetString("ReporteCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 	c.Nombre as NombreComic,p.Cantidad as CantidadComic,p.Valor as ValorComic FROM Usuario as u JOIN Pedido as p ON  u.ID = p.Usuario JOIN TipoDocumento as t ON u.TipoDocumento = t.Id JOIN Comic as c ON p.Comic = c.Id JOIN Compra as co ON co.Pedido = p.Guid  WHERE  u.NumeroDocumento = {0} AND p.Guid = &quot;{1}&quot;.
        /// </summary>
        public static string ReporteCompraDetalle {
            get {
                return ResourceManager.GetString("ReporteCompraDetalle", resourceCulture);
            }
        }
    }
}
